name: Pull Request

on: pull_request

jobs:
  rustfmt:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Check for idiomatic code
        run: cargo clippy --all-features --all-targets --all -- -D warnings
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Check for errors
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run builder tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path worker-build/Cargo.toml
          
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: v18.12.1

      - name: Install packages
        run: |
          sudo apt update
          sudo apt clean
          sudo apt install -y build-essential libssl-dev netcat libc++-dev
      - name: Install wasmpack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build local worker-build
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path ./worker-build --force --debug

      - name: Install npm dependencies
        shell: bash
        run: npm ci

      - name: Build worker
        shell: bash
        working-directory: ./worker-sandbox
        run: NO_MINIFY=1 worker-build --dev
        
      - name: Run tests
        shell: bash
        working-directory: ./worker-sandbox
        run: NODE_OPTIONS=--experimental-vm-modules npx vitest run
